services:
  client:
    container_name: hopswheel-client
    build:
      context: .\hopswheel.client
      dockerfile: .\Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      - server

  server:
    container_name: hopswheel-server
    build:
      context: .
      dockerfile: hopswheel.server\Web.Api\Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8080"
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    container_name: hopswheel-db
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_DB=hops-wheel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /pgadmin/password
      PGADMIN_LISTEN_POR: 80
    volumes:
      - ./pgadmin-password.txt:/pgadmin/password:ro
    ports:
      - 80:80
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge